import { data as M } from "./data.js";
import { engine as E } from "./engine.js";

'use strict';

var $=function(id){return document.getElementById(id);};

var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function wait(ms){return new Promise(function(resolve){setTimeout(resolve,ms);});}
function ensureResultCard(){var card=document.querySelector('.verdict-card');if(!card)return;card.innerHTML='<div class="pick-label"><span class="pick-dot"></span>Active pick</div><div class="pick-hero"><strong id="stage-verdict">—</strong><span class="pick-mark" id="stage-mark">M26</span></div><div class="verdict-company" id="stage-company">Ready for the next throw</div><div class="pick-badges"><span id="stage-country">Global universe</span><span id="stage-sector">All sectors</span><span id="stage-asset">Security</span><span id="stage-cap">All sizes</span></div><div class="pick-detail" id="stage-sub">Validated data · direct unbiased draw</div><div class="verdict-lock"><span class="lock-icon">▣</span><span><b>Selection locked</b><small id="stage-lock">The next outcome will be marked in the newspaper edition.</small></span></div>';}
function resetCard(detail){var n=detail&&detail.count!=null?detail.count:(E&&E.active?E.active.length:0),card=document.querySelector('.verdict-card');if(card)card.classList.remove('has-result');$('stage-verdict').textContent='—';$('stage-mark').textContent='M26';$('stage-company').textContent=n?'Ready for the next throw':'Choose a valid universe';$('stage-country').textContent=n?n+' eligible':'No active universe';$('stage-sector').textContent=n?'1 in '+n+' odds':'Broaden the filters';$('stage-asset').textContent='Direct crypto draw';$('stage-cap').textContent='Full edition';$('stage-sub').textContent=n?'Every eligible listing can be hit':'At least one security is required';$('stage-lock').textContent='The next outcome will be marked in the newspaper edition.';}
function populateCard(row){var d=row.security,card=document.querySelector('.verdict-card');if(card){card.classList.remove('has-result');void card.offsetWidth;card.classList.add('has-result');}$('stage-verdict').textContent=d.ticker;$('stage-mark').textContent=d.ticker.slice(0,4);$('stage-company').textContent=d.name;$('stage-country').textContent=d.country;$('stage-sector').textContent=d.sector;$('stage-asset').textContent=d.assetType;$('stage-cap').textContent=d.size+(d.assetType==='ETF'?' Fund':' Cap');$('stage-sub').textContent=d.exchange+' · '+d.currency+' · odds 1 in '+row.universeSize;$('stage-lock').textContent='Page '+row.page+', line '+row.line+' · throw '+row.no.toLocaleString('en-US')+'.';}
function targetLine(){return grid&&grid.querySelector('.stock-line.current-pick');}
function targetPoint(line){if(!line)return null;var ticker=line.querySelector('.stock-ticker'),r=(ticker||line).getBoundingClientRect();return{line:line,x:r.left+r.width*.72,y:r.top+r.height*.55};}
function dartSvg(){return '<svg viewBox="0 0 90 30"><polygon points="0,15 15,9 15,21" fill="#f1eee6"/><rect x="15" y="9" width="34" height="12" rx="2" fill="#d8a748"/><rect x="49" y="13" width="17" height="4" fill="#859198"/><polygon points="66,15 90,4 90,26" fill="#df4b3b"/><polygon points="66,15 90,4 90,15" fill="#f06a52"/></svg>';}
function markImpact(line){if(!line)return;var holder=line.querySelector('.news-pins');if(holder&&!holder.children.length){var pin=document.createElement('span');pin.className='news-pin';pin.innerHTML=dartSvg();holder.appendChild(pin);}line.classList.add('has-pin');var ring=document.createElement('span');ring.className='newspaper-impact';line.appendChild(ring);setTimeout(function(){ring.remove();},800);range.classList.remove('flash');void range.offsetWidth;range.classList.add('flash');setTimeout(function(){range.classList.remove('flash');},450);}
async function animate(){var target=targetPoint(targetLine());if(!target)return;if(reduced){markImpact(target.line);return;}await wait(190);var hand=$('hand').getBoundingClientRect(),a={x:hand.left+hand.width/2,y:hand.top+hand.height/2},b=target,dx=b.x-a.x,dy=b.y-a.y,d=Math.sqrt(dx*dx+dy*dy),angle=Math.atan2(dy,dx)*180/Math.PI,lift=Math.min(140,d*.18)+22,duration=610;var dart=document.createElement('div');dart.className='flight-dart-v4 newspaper-flight';dart.innerHTML=dartSvg();flight.appendChild(dart);var trail=document.createElement('div');trail.className='flight-trail';document.body.appendChild(trail);trail.style.left=a.x+'px';trail.style.top=a.y+'px';trail.style.width=Math.max(45,d*.35)+'px';trail.style.transform='rotate('+angle+'deg)';if(monkey)monkey.classList.add('release','throwing');var anim=dart.animate([{transform:'translate('+a.x+'px,'+a.y+'px) translate(-18px,-14px) rotate('+(angle-8)+'deg) scale(1.12)'},{transform:'translate('+(a.x+dx*.54)+'px,'+(a.y+dy*.54-lift)+'px) translate(-18px,-14px) rotate('+(angle+4)+'deg) scale(.7)',offset:.54},{transform:'translate('+b.x+'px,'+b.y+'px) translate(-18px,-14px) rotate('+(angle+11)+'deg) scale(.3)'}],{duration:duration,easing:'cubic-bezier(.28,.02,.2,1)',fill:'forwards'});trail.animate([{opacity:0,transform:'rotate('+angle+'deg) scaleX(.1)'},{opacity:.85,offset:.25,transform:'rotate('+angle+'deg) scaleX(1)'},{opacity:0,transform:'rotate('+angle+'deg) translateX('+(d*.52)+'px) scaleX(.2)'}],{duration:duration*.72,easing:'ease-out',fill:'forwards'});try{await anim.finished;}finally{dart.remove();trail.remove();if(monkey)monkey.classList.remove('release','throwing');markImpact(target.line);}}
ensureResultCard();
window.addEventListener('m26:universe',function(event){resetCard(event.detail);});
window.addEventListener('m26:result',function(event){populateCard(event.detail);animate();});
var reset=$('reset');if(reset)reset.addEventListener('click',function(){setTimeout(function(){resetCard({count:E&&E.active?E.active.length:0});},0);});
var audit=$('audit');if(audit){new MutationObserver(function(){if(audit.querySelector('.control-copy'))return;var close=/close/i.test(audit.textContent);audit.innerHTML='<span class="control-icon">▦</span><span class="control-copy"><b>'+(close?'Close audit':'Audit edition')+'</b><small>'+(close?'Return to clean view':'Show page and line data')+'</small></span>';}).observe(audit,{childList:true,subtree:true});}
