(function(global){
'use strict';
var M=global.M26,E=M.engine={pageSize:24,active:[],edition:[],ledger:[],throws:0,counts:{},label:'Global 360',rng:{calls:0,rejections:0,last:null}};
var cryptoOK=!!(global.crypto&&global.crypto.getRandomValues),buf=cryptoOK?new Uint32Array(1):null;
E.rand=function(n){if(!Number.isInteger(n)||n<1)throw new Error('Random range must be a positive integer');var r,rej=0;if(!cryptoOK){r=Math.floor(Math.random()*n);E.rng.calls++;E.rng.last={raw:-1,index:r,rejections:0};return r;}var limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(buf);r=buf[0];E.rng.calls++;if(r>=limit){rej++;E.rng.rejections++;}}while(r>=limit);E.rng.last={raw:r,index:r%n,rejections:rej};return r%n;};
E.shuffle=function(a){for(var i=a.length-1;i>0;i--){var j=E.rand(i+1),t=a[i];a[i]=a[j];a[j]=t;}return a;};
E.reset=function(){E.edition=[];E.ledger=[];E.throws=0;E.counts={};E.rng={calls:0,rejections:0,last:null};};
E.setUniverse=function(rows,label){E.active=rows.slice();E.label=label;E.reset();if(rows.length)E.newEdition();};
E.newEdition=function(){var before=E.rng.calls;E.edition=E.shuffle(E.active.slice());return E.rng.calls-before;};
E.throw=function(){if(!E.active.length)throw new Error('At least one eligible security is required');var pick=E.rand(E.active.length),selectionRng=Object.assign({},E.rng.last),security=E.active[pick],editionCalls=E.newEdition(),position=E.edition.findIndex(function(d){return d.id===security.id;}),spread=Math.floor(position/E.pageSize)+1,within=position%E.pageSize,side=within<12?'left':'right',page=(spread-1)*2+(side==='left'?1:2),line=within%12+1;E.throws++;E.counts[security.id]=(E.counts[security.id]||0)+1;var row={no:E.throws,spread:spread,page:page,line:line,side:side,location:'P'+page+' · L'+line,security:security,selectionIndex:pick,universeSize:E.active.length,universeLabel:E.label,version:M.meta.version,editionCalls:editionCalls,rng:selectionRng};E.ledger.unshift(row);return row;};
E.batch=function(n){var last;for(var i=0;i<n;i++)last=E.throw();return last;};
E.expectedDistinct=function(){var n=E.active.length;return n&&E.throws?n*(1-Math.pow((n-1)/n,E.throws)):0;};
E.entropy=function(){if(E.throws<2)return null;var h=0;Object.keys(E.counts).forEach(function(k){var p=E.counts[k]/E.throws;h-=p*Math.log(p);});var max=Math.log(Math.min(E.active.length,E.throws));return max?h/max:null;};
E.chi=function(){if(!E.throws||!E.active.length)return null;var expected=E.throws/E.active.length,sum=0;E.active.forEach(function(d){var diff=(E.counts[d.id]||0)-expected;sum+=diff*diff/expected;});return sum;};
function logGamma(z){var c=[676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z--;var x=.9999999999998099;for(var i=0;i<c.length;i++)x+=c[i]/(z+i+1);var t=z+c.length-.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x);}
function gammaQ(a,x){if(x<0||a<=0)return NaN;if(x===0)return 1;var gl=logGamma(a),eps=1e-12,max=300;if(x<a+1){var ap=a,del=1/a,sum=del;for(var n=1;n<=max;n++){ap++;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*eps)break;}return Math.max(0,Math.min(1,1-sum*Math.exp(-x+a*Math.log(x)-gl)));}var b=x+1-a,c=1e300,d=1/b,h=d;for(var i=1;i<=max;i++){var an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;var q=d*c;h*=q;if(Math.abs(q-1)<eps)break;}return Math.max(0,Math.min(1,Math.exp(-x+a*Math.log(x)-gl)*h));}
E.pValue=function(){var n=E.active.length;if(E.throws<n||n<2)return null;return gammaQ((n-1)/2,E.chi()/2);};
E.csv=function(){function q(v){v=String(v==null?'':v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}var h=['throw','page','line','security_id','ticker','name','asset_type','market_group','country','region','exchange','currency','sector','industry','size_band','selection_index','universe_size','universe_label','version'];var b=E.ledger.slice().reverse().map(function(r){var d=r.security;return [r.no,r.page,r.line,d.id,d.ticker,d.name,d.assetType,d.group,d.country,d.region,d.exchange,d.currency,d.sector,d.industry,d.size,r.selectionIndex,r.universeSize,r.universeLabel,r.version].map(q).join(',');});return [h.join(',')].concat(b).join('\n');};
})(window);
