(function(global){
'use strict';
var M=global.M26,E=M.engine,$=function(id){return document.getElementById(id)},all=[],preset='global',slots=[],busy=false,audit=false;
var grid=$('grid'),plaque=$('plaque'),toast=$('toast'),live=$('live');
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(function(){toast.classList.remove('show');},1700);}
function status(t,kind){$('top-status').textContent=t;var n=document.querySelector('.live-state');n.classList.remove('ready','error');if(kind)n.classList.add(kind);}
function option(select,values,label){select.innerHTML='<option value="">'+label+'</option>'+values.map(function(v){return '<option>'+esc(v)+'</option>';}).join('');}
function buildWall(){for(var i=0;i<25;i++){var s=document.createElement('div');s.className='slot';s.innerHTML='<div class="card"><div class="face back"><span class="cell-id">'+String.fromCharCode(65+Math.floor(i/5))+(i%5+1)+'</span><span class="hit-count"></span></div><div class="face front"><span class="ticker">—</span><span class="type">Loading</span></div></div><div class="pins"></div>';grid.appendChild(s);slots.push(s);}}
function paintDeal(){slots.forEach(function(s,i){var d=E.deal[i],f=s.querySelector('.front');if(!d)return;f.style.setProperty('--rg',{'Mega':'var(--gold-2)','Large':'var(--green)','Mid':'var(--teal)','Small':'var(--purple)','Micro':'var(--red-2)'}[d.size]||'var(--blue)');f.querySelector('.ticker').textContent=d.ticker;f.querySelector('.type').textContent=d.country+' · '+d.assetType;s.classList.remove('faceup');});grid.classList.remove('audit');audit=false;$('audit').textContent='Audit wall';}
function filters(){var base=M.presets[preset][1],r=$('filter-region').value,s=$('filter-sector').value,c=$('filter-cap').value,a=$('filter-asset').value,q=$('filter-search').value.trim().toLowerCase();return all.filter(function(d){if(!base(d)||r&&d.region!==r||s&&d.sector!==s||c&&d.size!==c||a&&d.assetType!==a)return false;if(q&&[d.id,d.ticker,d.name,d.country,d.region,d.sector,d.industry,d.group].join(' ').toLowerCase().indexOf(q)<0)return false;return true;});}
function apply(announce){var rows=filters(),label=M.presets[preset][0];E.setUniverse(rows,label);clearVisual();if(rows.length>=25)paintDeal();renderUniverse();render();if(announce)notify(rows.length+' securities eligible');}
function clearVisual(){slots.forEach(function(s){s.classList.remove('faceup','struck');s.querySelector('.pins').innerHTML='';var h=s.querySelector('.hit-count');h.textContent='';h.classList.remove('on');});}
function renderUniverse(){var n=E.active.length,markets=M.unique(E.active.map(function(d){return d.country;})),sectors=M.unique(E.active.map(function(d){return d.sector;})),assets=M.countBy(E.active,'assetType'),regions=M.countBy(E.active,'region'),largest=Object.keys(regions).sort(function(a,b){return regions[b]-regions[a];})[0]||'—';$('active-count').textContent=n;$('diag-countries').textContent=markets.length;$('diag-sectors').textContent=sectors.length;$('diag-assets').textContent=(assets.Stock||0)+' / '+(assets.ETF||0);$('diag-region').textContent=largest==='—'?'—':largest+' ('+regions[largest]+')';$('diag-odds').textContent=n?'1 in '+n:'—';$('diag-status').textContent=n>=25?'Validated beta':'Insufficient';$('hero-kicker').textContent=n+' securities · 25 blind cards · zero conviction';$('meta-count').textContent=n+' active / '+all.length+' total';$('k-universe').textContent=n||'—';$('k-probability').textContent=n?'1 / '+n+' per security':'probability pending';if(n>=25){$('probability-equation').innerHTML='P(pick) = 25/'+n+' × 1/25 = <strong>1/'+n+'</strong>';$('probability-copy').textContent='Every eligible security receives exactly '+(100/n).toFixed(n>200?3:2)+'% per throw.';$('eligibility-warning').hidden=true;$('stage-verdict').textContent='The experiment is armed.';$('stage-sub').textContent=M.presets[preset][0]+' · one fair throw to begin.';plaque.innerHTML='<span class="plaque-label">Universe ready</span><span class="plaque-name">'+n+' eligible securities · '+M.presets[preset][0]+'</span>';}else{$('probability-equation').textContent='P(pick) = unavailable';$('probability-copy').textContent='At least 25 eligible securities are required.';$('eligibility-warning').hidden=false;$('eligibility-warning').textContent='Only '+n+' securities match. Broaden the filters to at least 25.';$('stage-verdict').textContent='Universe too narrow.';}sync();}
function sync(){var ok=E.active.length>=25;['throw','throw10','throw100','throw1000','audit'].forEach(function(id){$(id).disabled=busy||!ok;});$('copy').disabled=busy||!E.ledger.length;$('download').disabled=busy||!E.ledger.length;$('reset').disabled=busy||!all.length;}
function comparison(el,field,order,limit){var base=M.countBy(E.active,field),obs={};E.ledger.forEach(function(r){var v=r.security[field];obs[v]=(obs[v]||0)+1;});var names=order||M.unique(Object.keys(base).concat(Object.keys(obs)));names=names.filter(function(n){return base[n]||obs[n];}).sort(function(a,b){return (obs[b]||0)-(obs[a]||0)||(base[b]||0)-(base[a]||0);});if(limit)names=names.slice(0,limit);el.innerHTML=names.map(function(n){var bp=E.active.length?(base[n]||0)/E.active.length*100:0,op=E.throws?(obs[n]||0)/E.throws*100:0;return '<div class="compare-row"><div class="compare-head"><span>'+esc(n)+'</span><span>'+(E.throws?op.toFixed(1)+'%':'—')+' / '+bp.toFixed(1)+'%</span></div><div class="compare-track"><div class="compare-base" style="width:'+bp+'%"></div><div class="compare-observed" style="width:'+op+'%"></div></div></div>';}).join('');}
function render(){var n=E.active.length,distinct=Object.keys(E.counts).length,ent=E.entropy(),p=E.pValue();$('k-throws').textContent=E.throws.toLocaleString('en-US');$('k-distinct').innerHTML=distinct+' <small>/ '+n+'</small>';$('k-distinct-note').textContent='expected '+E.expectedDistinct().toFixed(1);$('k-repeat').textContent=(E.throws?(E.throws-distinct)/E.throws*100:0).toFixed(1)+'%';$('k-entropy').textContent=ent==null?'—':ent.toFixed(3);var fair=$('k-fair'),note=$('k-fair-note');fair.className='kpi-value';if(p==null){fair.textContent='—';note.textContent=n?'exploratory after '+n+' throws':'awaiting universe';}else{fair.textContent='p '+p.toFixed(3);if(E.throws<5*n){fair.classList.add('warn');note.textContent='exploratory · robust near '+(5*n).toLocaleString('en-US');}else if(p>=.05){fair.classList.add('ok');note.textContent='consistent with equal 1/'+n;}else{fair.classList.add('bad');note.textContent='unusually uneven sample';}}
var ranked=Object.keys(E.counts).map(function(id){return {d:E.active.find(function(x){return x.id===id;}),c:E.counts[id]};}).filter(function(x){return x.d;}).sort(function(a,b){return b.c-a.c;}).slice(0,12);$('distribution').innerHTML=ranked.length?ranked.map(function(x){return '<div class="rank-row"><div class="rank-name">'+esc(x.d.ticker)+'</div><div class="rank-track"><div class="rank-fill" style="width:'+(x.c/ranked[0].c*100)+'%"></div></div><div class="rank-value">'+x.c+'</div></div>';}).join(''):'<div class="empty-chart">No selections yet.<br>Throw the first dart.</div>';$('dist-meta').textContent=E.throws?E.throws.toLocaleString('en-US')+' observations · top 12':'No observations';comparison($('regions-chart'),'region',null,8);comparison($('sectors-chart'),'sector',null,10);comparison($('caps-chart'),'size',M.capOrder);comparison($('assets-chart'),'assetType',['Stock','ETF']);renderLedger();sync();}
function renderLedger(){var b=$('ledger');if(!E.ledger.length){b.innerHTML='<tr><td class="empty" colspan="12">Throw a dart to open the first card.</td></tr>';return;}b.innerHTML=E.ledger.slice(0,500).map(function(r){var d=r.security,cl=M.capClass[d.size]||'large';return '<tr><td>'+r.no+'</td><td>'+r.cell+'</td><td class="ticker-cell">'+esc(d.ticker)+'</td><td class="company-cell">'+esc(d.name)+'</td><td>'+esc(d.country)+'</td><td>'+esc(d.region)+'</td><td>'+esc(d.sector)+'</td><td>'+esc(d.industry)+'</td><td><span class="chip '+cl+'">'+esc(d.size)+'</span></td><td>'+esc(d.assetType)+'</td><td>'+esc(d.exchange)+'</td><td>'+esc(d.group)+'</td></tr>';}).join('');}
function pin(i){var s=slots[i],w=s.querySelector('.pins'),p=document.createElement('div');p.className='pin';p.style.left=(20+Math.random()*60)+'%';p.style.top=(18+Math.random()*64)+'%';p.style.transform='translate(0,-50%) rotate('+(-53+Math.random()*28)+'deg) scale(.88)';p.innerHTML='<svg viewBox="0 0 78 20" width="29" height="8"><polygon points="0,10 13,5.5 13,14.5" fill="#eee"/><rect x="13" y="5.5" width="28" height="9" fill="#d8a748"/><polygon points="55,10 78,2 78,18" fill="#d64d3b"/></svg>';w.appendChild(p);s.classList.add('faceup','struck');setTimeout(function(){s.classList.remove('struck');},230);var h=s.querySelector('.hit-count');h.textContent=E.cellCounts[i];h.classList.add('on');}
function showResult(r){paintDeal();var i=(r.cell.charCodeAt(0)-65)*5+Number(r.cell.slice(1))-1,p=M.capClass[r.security.size]||'large';pin(i);plaque.innerHTML='<span class="plaque-label">'+r.cell+'</span><span class="plaque-ticker">'+esc(r.security.ticker)+'</span><span class="plaque-name">'+esc(r.security.name+' · '+r.security.country+' · '+r.security.sector)+'</span><span class="chip '+p+'">'+r.security.size+'</span>';$('stage-verdict').textContent=r.security.ticker+' selected';$('stage-sub').textContent=r.security.name+' · '+r.security.country+' · '+r.security.size;$('entropy').innerHTML='<b>DEAL</b> '+E.active.length+' eligible → 25 hidden cards · <b>THROW</b> raw <span class="v">'+(r.rng.raw<0?'n/a':'0x'+r.rng.raw.toString(16).toUpperCase().padStart(8,'0'))+'</span> → <span class="v">'+r.cell+'</span> · cumulative RNG calls <span class="v">'+E.rng.calls.toLocaleString('en-US')+'</span>';render();live.textContent='Selected '+r.security.ticker+', '+r.security.name;}
async function run(n){if(busy)return;busy=true;sync();status('Simulation running');try{var r;if(n===1){document.getElementById('monkey').classList.add('winding');await new Promise(function(x){setTimeout(x,260);});document.getElementById('monkey').classList.remove('winding');document.getElementById('monkey').classList.add('release','throwing');r=E.throw();await new Promise(function(x){setTimeout(x,180);});document.getElementById('monkey').classList.remove('release','throwing');}else{r=E.batch(n);}showResult(r);if(n>1)notify(n.toLocaleString('en-US')+' fair throws completed');}catch(e){notify(e.message);}finally{busy=false;status('Global 360 validated','ready');sync();}}
function download(){var blob=new Blob([E.csv()],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='monkey26-ledger-'+new Date().toISOString().slice(0,10)+'.csv';a.click();URL.revokeObjectURL(u);}
function bind(){document.querySelectorAll('.preset').forEach(function(b){b.onclick=function(){preset=b.dataset.preset;document.querySelectorAll('.preset').forEach(function(x){x.classList.toggle('active',x===b);});['filter-region','filter-sector','filter-cap','filter-asset','filter-search'].forEach(function(id){$(id).value='';});apply(true);};});['filter-region','filter-sector','filter-cap','filter-asset'].forEach(function(id){$(id).onchange=function(){apply(true);};});var t;$('filter-search').oninput=function(){clearTimeout(t);t=setTimeout(function(){apply(false);},180);};$('clear-filters').onclick=function(){['filter-region','filter-sector','filter-cap','filter-asset','filter-search'].forEach(function(id){$(id).value='';});apply(true);};$('throw').onclick=function(){run(1);};$('throw10').onclick=function(){run(10);};$('throw100').onclick=function(){run(100);};$('throw1000').onclick=function(){run(1000);};$('audit').onclick=function(){audit=!audit;grid.classList.toggle('audit',audit);$('audit').textContent=audit?'Hide wall':'Audit wall';};$('reset').onclick=function(){E.reset();clearVisual();if(E.active.length>=25){E.newDeal();paintDeal();}render();notify('Experiment reset');};$('copy').onclick=function(){navigator.clipboard?navigator.clipboard.writeText(E.csv()).then(function(){notify('Ledger copied');}):notify('Clipboard unavailable');};$('download').onclick=download;document.addEventListener('keydown',function(e){if(e.code==='Space'&&!e.repeat&&!/INPUT|SELECT|BUTTON/.test(document.activeElement.tagName)){e.preventDefault();run(1);}});}
async function init(){buildWall();bind();status('Loading Global 360');try{all=await M.load();option($('filter-region'),M.unique(all.map(function(d){return d.region;})),'All regions');option($('filter-sector'),M.unique(all.map(function(d){return d.sector;})),'All sectors');option($('filter-cap'),M.capOrder,'All size bands');option($('filter-asset'),M.unique(all.map(function(d){return d.assetType;})),'All instruments');$('meta-version').textContent=M.meta.version;$('meta-date').textContent='Snapshot 25 Jul 2026';$('footer-data').textContent=M.meta.name+' · '+M.meta.version;apply(false);status('Global 360 validated','ready');notify('Global 360 universe loaded');}catch(e){status('Universe load failed','error');$('eligibility-warning').hidden=false;$('eligibility-warning').textContent=e.message;console.error(e);}}
init();
})(window);
